### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by hektor-7** [MhL5/Meta-Blog#8]
> [!WARNING]
> **SECURITY BUG**

Add `CSRF` protection in order to safeguard the APIs against form submissions. 
According to CORS, `localhost:5000` is considered an entirely different website, but it can still send requests using form data.

example:
https://github.com/MhL5/Meta-Blog/assets/136856523/7f6fde44-fc72-4549-943d-4a89509a341f

**Comment by MhL5** [comment]
- [x] #9 csrf security issue solved

**Comment by MhL5** [comment]
feel free to open another issue
